const fs = require('fs');

fs.readdir('./resources/assets/components/Formfields', function (err, files) {
    if (err) throw err;

    let content = "// This file is automatically generated. Run `npm run scripts` or any other command to re-generate it!\n\n";
    content += "import { defineAsyncComponent } from 'vue';\n\n";
    content += "export default {\n";
    files.forEach((file) => {
        content += `    Formfield${file}Builder: defineAsyncComponent(() => import(/* webpackChunkName: "Formfield${file}Builder" */'@components/Formfields/${file}/Builder')),\n`;
        content += `    Formfield${file}: defineAsyncComponent(() => import(/* webpackChunkName: "Formfield${file}" */'@components/Formfields/${file}/Formfield')),\n`;
    });

    content += `    BreadBuilderList: defineAsyncComponent(() => import(/* webpackChunkName: "BreadBuilderList" */'@components/Builder/List')),\n`;
    content += `    BreadBuilderView: defineAsyncComponent(() => import(/* webpackChunkName: "BreadBuilderView" */'@components/Builder/View')),\n`;

    content += "};";

    fs.writeFile('resources/assets/js/formfields.js', content, (err) => {
        if (err) throw err;
        console.log('Formfields file generated at "resources/assets/js/formfields.js"');
    });
});