const fs = require('fs');
const icons = require('../node_modules/@heroicons/vue/outline/index');

let content = "// This file is automatically generated. Run `npm run scripts` or any other command to re-generate it!\n\n";
content += "import { defineAsyncComponent } from 'vue';\n";
content += "import IconLoader from '../components/UI/IconLoader';\n\n";
content += "export default {\n";

Object.keys(icons).forEach(icon => {
    let name = icon.replace('Icon', '');
    content += `    ${name}: defineAsyncComponent({ loader: () => import(/* webpackChunkName: "${icon}" */'@heroicons/vue/outline/esm/${icon}'), loadingComponent: IconLoader }),\n`;
});

// Static Voyager icons
content += `    Bread: defineAsyncComponent(() => import(/* webpackChunkName: "BreadIcon" */'./icons/bread')),\n`;
content += `    Helm: defineAsyncComponent(() => import(/* webpackChunkName: "HelmIcon" */'./icons/helm')),\n`;

content += "}";

fs.writeFile('resources/assets/js/icons.js', content, (err) => {
    if (err) throw err;
    console.log('Icons file generated at "resources/assets/js/icons.js"');
});